/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.util.converter.DateTimeStringConverter;

import java.io.IOException;

import static javafx.application.Application.launch;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

public class App extends Application {

    public static void main(String[] args) { launch(args);}

    //@Override
    public void start(Stage stage) throws IOException {

        stage.setTitle("Lab 4");

        Button register = new Button("Register");
        register.setTranslateX(50);
        register.setTranslateY(600);

        Label l1 = new Label("Username");
        TextField t1 = new TextField();

        Label l2 = new Label("Password");
        PasswordField password = new PasswordField();
        password.setPromptText("Enter");

        Label l3 = new Label("Full Name");
        TextField t3 = new TextField();

        Label l4 = new Label("Email");
        TextField t4 = new TextField();

        Label l5 = new Label("Phone Number");
        TextField number = new TextField();
        DecimalFormat num = new DecimalFormat("###-###-####");
        //num.format(number);
        //number.setTextFormatter(Integer.valueOf(num));

        Label l6 = new Label("Date of Birth");
        TextField birthdate = new TextField();
        SimpleDateFormat date = new SimpleDateFormat("dd/mm/yyyy");
        birthdate.setTextFormatter(new TextFormatter<>(new DateTimeStringConverter(date)));

        register.setOnAction(e -> {

            String username = t1.getText();
            String pass = password.getText();
            String name = t3.getText();
            String email = t4.getText();
            String phone_num = number.getText();
            String bdate = birthdate.getText();
            //num.format(phone_num);
            System.out.println(username + ": " + pass + "\n" + name + " | " + email);
            System.out.println(phone_num);
            System.out.println(bdate);

        });

        VBox box = new VBox(10);
        box.setAlignment(Pos.TOP_LEFT);

        box.setPadding(new Insets(50, 750 , 100, 50));
        box.setFillWidth(true);

        box.getChildren().addAll(l1, t1, l2, password, l3, t3, l4, t4, l5, number, l6, birthdate);
        Group group = new Group(register, box);
        Scene scene = new Scene(group, 1280, 720);
        stage.setScene(scene);
        stage.show();
        //FXMLLoader fxmlLoader = new FXMLLoader(HelloApplication.class.getResource("hello-view.fxml"));
//        Scene scene = new Scene(fxmlLoader.load(), 320, 240);
//        stage.setTitle("Hello!");
//        stage.setScene(scene);
//        stage.show();
    }

    public String getGreeting() {
        return "Hello World!";
    }


}
